### PR TITLE
Working box

### PR DESCRIPTION
**Pull request by buggedbeatle998**
This is a fully working box. I also added it as an example to the room

### CODE REVIEW

**Comment by TML233** [comment]
Good addition!
I'll check the code and merge it later.
Thanks!

**Comment by coreknee** [comment]
still waiting... @TML233

**Comment by Animeliqite** [comment]
bro disconnected

**Comment by Ceyase** [comment]
Code checking complete.
Most of the code does not meet quality requirements.
Quality optimization has been performed.
Can be merged.

**Pull request merged**
